GET http://localhost:3000/api/book
###
POST http://localhost:3000/api/book

Content-Type: application/json

{
    "title": "Book 3",
    "year": 2015,
    "rating": 1
}

###
POST http://localhost:3000/api/author

Content-Type: application/json

{
    "name": "Grady book1",
    "town": "Kansas",
    "bookId": "625e5f11a96b6c03f26d9afc"
}

###
GET http://localhost:3000/api/author
###
GET http://localhost:3000/api/book-authors
###

GET http://localhost:3000/api/book-agg2